apiVersion: apps/v1

kind: Deployment

metadata:

  name: vms
  labels:
    app: vms
spec:

  replicas: 1
  selector:
    matchLabels:
      app: vms
  template:

    metadata:

      labels:

        app: vms

    spec:

      containers:

      - name: vms

        image: __ACR__/lotusbetaanalyticsvmsnode_web

        ports:

        - containerPort: 6379

          name: vmsservice


---

apiVersion: v1

kind: Service

metadata:

  name: vms

spec:
  type: ClusterIP
  ports:

  - port: 6379

  selector:

    app: vms

---
apiVersion: v1

kind: Service

metadata:

  name: vms

spec:

  type: LoadBalancer

  ports:

  - port: 80

  selector:
    app: vms