
apiVersion: apps/v1

kind: Deployment

metadata:

  name: vmsnode
  namespace: vms-node

spec:

  replicas: 1

  strategy:
    type: RollingUpdate
    rollingUpdate:

      maxSurge: 1

      maxUnavailable: 1

  minReadySeconds: 5 
  selector:
    matchLabels:
      app: vmsnode
  template:

    metadata:

      labels:

        app: vmsnode

    spec:

      containers:

      - name: vmsnode

        image: __ACR__/lotusbetaanalyticsvmsnode_web

        imagePullPolicy: Always

        ports:

        - containerPort: 8000

        resources:

          requests:

            cpu: 250m

          limits:

            cpu: 500m

        

---
---

apiVersion: v1

kind: Service

metadata:

  name: vmsnode

spec:
  type: ClusterIP
  ports:

  - port: 8000
  

  selector:

    app: vmsnode

---
apiVersion: v1

kind: Service

metadata:

  name: vms

spec:

  type: LoadBalancer

  ports:

  - port: 8000

  selector:
    app: vmsnode

  