apiVersion: apps/v1

kind: Deployment

metadata:

  name: vms
  namespace: vms-node
  labels:
    app: vms
spec:

  replicas: 1
  selector:
    matchLabels:
      app: vms
  template:

    metadata:

      labels:

        app: vms

    spec:

      containers:

      - name: vms

        image: __ACR__/lotusbetaanalyticsvmsnode_web:latest

        ports:

        - containerPort: 6379
        
         


---

apiVersion: v1

kind: Service

metadata:

  name: vms

spec:
  type: ClusterIP
  ports:

  - port: 6350
  

  selector:

    app: vms

---
apiVersion: v1

kind: Service

metadata:

  name: vms

spec:

  type: LoadBalancer

  ports:

  - port: 80

  selector:
    app: vms

  